import { TechnologyIconKey } from "@/client/portfolio/types";
import type { IconType } from "react-icons";
import { GrTechnology } from "react-icons/gr";
import {
  SiReact,
  SiNextdotjs,
  SiNodedotjs,
  SiJavascript,
  SiTypescript,
  SiMongodb,
  SiGraphql,
  SiApollographql,
  SiRedux,
  SiMui,
  SiFirebase,
  SiStripe,
  SiVuedotjs,
  SiDjango,
  SiPython,
  SiTailwindcss,
  SiStorybook,
  SiRadixui,
  SiStyledcomponents,
  SiJira,
  SiGithub,
  SiSanity,
  SiDocusaurus,
  SiShopify,
  SiThreedotjs,
  SiOpenai,
  SiPostgresql,
  SiExpress,
  SiMeteor,
} from "react-icons/si";
import { VscAzure } from "react-icons/vsc";

export const technologyIcons: Record<TechnologyIconKey, IconType> = {
  javascript: SiJavascript,
  azuredevops: VscAzure,
  typescript: SiTypescript,
  react: SiReact,
  nextjs: SiNextdotjs,
  nodejs: SiNodedotjs,
  meteor: SiMeteor,
  mongodb: SiMongodb,
  graphql: SiGraphql,
  apollo: SiApollographql,
  redux: SiRedux,
  materialui: SiMui,
  reactnative: SiReact,
  firebase: SiFirebase,
  stripe: SiStripe,
  vue: SiVuedotjs,
  django: SiDjango,
  python: SiPython,
  tailwind: SiTailwindcss,
  storybook: SiStorybook,
  radixui: SiRadixui,
  styledcomponents: SiStyledcomponents,
  jira: SiJira,
  git: SiGithub,
  sanity: SiSanity,
  docusaurus: SiDocusaurus,
  shopify: SiShopify,
  threejs: SiThreedotjs,
  openai: SiOpenai,
  postgres: SiPostgresql,
  express: SiExpress,
  unknown: GrTechnology,
};
